[package]
name = "sudokutext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"
lazy_static = "1.4.0"
strum_macros = "0.26.2"
ansi_term = "0.12.1"
rand = "0.8.5"
csv = "1.3.0"